#ifndef ResID_h__
#define ResID_h__

#define RES_ID_LIST( op )\
	op( IMAGE_LOADING_SCREEN )\
	op( IMAGE_LOADERBAR )\
	\
	op( IMAGE_DIALOG_BUTTON )\
	op( IMAGE_DIALOG_BACK )\
	\
	op( IMAGE_CURSOR_POINTER )\
	op( IMAGE_CURSOR_HAND )\
	op( IMAGE_CURSOR_DRAGGING )\
	op( IMAGE_CURSOR_TEXT )\
	\
	op( IMAGE_SUNGLOW )\
	\
	op( IMAGE_MM_BACK )\
	op( IMAGE_MM_GAUNTLET )\
	op( IMAGE_MM_ARCADE )\
	op( IMAGE_MM_MOREGAMES )\
	op( IMAGE_MM_OPTIONS )\
	op( IMAGE_MM_QUIT )\
	op( IMAGE_MM_EYELEFT )\
	op( IMAGE_MM_EYERIGHT )\
	op( IMAGE_MM_EYEMASK )\
	op( IMAGE_MM_SUN )\
	op( IMAGE_MM_SKY )\
	op( IMAGE_MM_HAT )\
	\
	op( IMAGE_ADVSKY )\
	op( IMAGE_ADVBACK )\
	op( IMAGE_ADVMIDDLE )\
	op( IMAGE_ADVTEMPLE1 )\
	op( IMAGE_ADVTEMPLE2 )\
	op( IMAGE_ADVTEMPLE3 )\
	op( IMAGE_ADVTEMPLE4 )\
	op( IMAGE_ADVTEMPLE2V )\
	op( IMAGE_ADVTEMPLE3V )\
	op( IMAGE_ADVDOOR1A )\
	op( IMAGE_ADVDOOR1B )\
	op( IMAGE_ADVDOOR1C )\
	op( IMAGE_ADVDOOR2A )\
	op( IMAGE_ADVDOOR2B )\
	op( IMAGE_ADVDOOR2C )\
	op( IMAGE_ADVDOOR3A )\
	op( IMAGE_ADVDOOR3B )\
	op( IMAGE_ADVDOOR3C )\
	op( IMAGE_ADVDOOR4A )\
	op( IMAGE_ADVDOOR4B )\
	op( IMAGE_ADVDOOR4C )\
	op( IMAGE_ADVMAINMENUBUTTON )\
	op( IMAGE_ADVPLAYBUTTON )\
	op( IMAGE_ADVSTAGE )\
	op( IMAGE_ADVTITLE )\
	op( IMAGE_ADVHIGHSCORE )\
	\
	op( IMAGE_BLUE_BALL  )\
	op( IMAGE_YELLOW_BALL)\
	op( IMAGE_RED_BALL)\
	op( IMAGE_GREEN_BALL)\
	op( IMAGE_PURPLE_BALL)\
	op( IMAGE_WHITE_BALL)\
	op( IMAGE_NEXT_BALL)\
	\
	op( IMAGE_BALL_ALPHA)\
	op( IMAGE_BALL_SHADOW)\
	\
	op( IMAGE_BLUE_ACCURACY )\
	op( IMAGE_YELLOW_ACCURACY )\
	op( IMAGE_RED_ACCURACY )\
	op( IMAGE_GREEN_ACCURACY )\
	op( IMAGE_PURPLE_ACCURACY )\
	op( IMAGE_WHITE_ACCURACY )\
	\
	op( IMAGE_BLUE_BACKWARDS )\
	op( IMAGE_YELLOW_BACKWARDS )\
	op( IMAGE_RED_BACKWARDS )\
	op( IMAGE_GREEN_BACKWARDS )\
	op( IMAGE_PURPLE_BACKWARDS )\
	op( IMAGE_WHITE_BACKWARDS )\
	\
	op( IMAGE_BLUE_SLOW )\
	op( IMAGE_YELLOW_SLOW )\
	op( IMAGE_RED_SLOW )\
	op( IMAGE_GREEN_SLOW )\
	op( IMAGE_PURPLE_SLOW )\
	op( IMAGE_WHITE_SLOW )\
	\
	op( IMAGE_GRAY_EXPLOSION )\
	op( IMAGE_EXPLOSION )\
	\
	op( IMAGE_BLUE_BOMB )\
	op( IMAGE_YELLOW_BOMB )\
	op( IMAGE_RED_BOMB )\
	op( IMAGE_GREEN_BOMB )\
	op( IMAGE_PURPLE_BOMB )\
	op( IMAGE_WHITE_BOMB )\
	\
	op( IMAGE_BLUE_LIGHT )\
	op( IMAGE_YELLOW_LIGHT )\
	op( IMAGE_RED_LIGHT )\
	op( IMAGE_GREEN_LIGHT )\
	op( IMAGE_PURPLE_LIGHT )\
	op( IMAGE_WHITE_LIGHT )\
	\
	op( IMAGE_BACKWARDS_LIGHT )\
	op( IMAGE_ACCURACY_LIGHT )\
	op( IMAGE_SLOW_LIGHT )\
	\
	op( IMAGE_SPARKLE )\
	\
	op( IMAGE_SHOOTER_BOTTOM )\
	op( IMAGE_SHOOTER_TOP )\
	op( IMAGE_SHOOTER_TONGUE )\
	op( IMAGE_EYE_BLINK )\
	\
	op( IMAGE_DIALOG_CHECKBOX )\
	op( IMAGE_DIALOG_CHECKBOXCAP )\
	op( IMAGE_DIALOG_CHECKBOXLINE )\
	op( IMAGE_SLIDER_TRACK )\
	op( IMAGE_SLIDER_THUMB )\
	op( IMAGE_UPDATE_BAR )\
	op( IMAGE_GOD_HEAD )\
	\
	op( IMAGE_HOLE )\
	op( IMAGE_HOLE_COVER )\
	op( IMAGE_COIN )\
	op( IMAGE_RIGHT_MOUSE )\
	\
	op( IMAGE_MENU_BAR )\
	op( IMAGE_MENU_BUTTON )\
	op( IMAGE_ZUMA_BAR )\
	op( IMAGE_ZUMA_BAR_DONE )\
	op( IMAGE_FROG_LIVES )\
	\
	op( SOUND_BALLCLICK1 )\
	op( SOUND_BALLCLICK2 )\
	op( SOUND_BALLFIRE )\
	op( SOUND_WARNING )\
	op( SOUND_EXPLODE )\
	op( SOUND_EARTHQUAKE )\
	op( SOUND_FROGLAND)\
	op( SOUND_JEWEL_APPEAR )\
	op( SOUND_JEWEL_DISAPPEAR )\
	op( SOUND_JEWEL_HIT )\
	op( SOUND_CHAIN_BONUS )\
	op( SOUND_GAP_BONUS )\
	op( SOUND_ROLLING )\
	op( SOUND_EXTRA_LIFE )\
	\
	op( SOUND_SLOWDOWN_BALL )\
	op( SOUND_BACKWARDS_BALL )\
	op( SOUND_ACCURACY_BALL )\
	op( SOUND_TRAIL_LIGHT )\
	op( SOUND_TRAIL_LIGHT_END )\
	op( SOUND_GAME_START )\
	op( SOUND_LEVEL_UP )\
	op( SOUND_BAR_FULL )\
	op( SOUND_LOST_LIFE )\
	op( SOUND_GAME_OVER )\
	op( SOUND_STAGE_COMPLETE )\
	op( SOUND_TEMPLE_COMPLETE )\
	op( SOUND_BONUS_EXPLOSION )\
	\
	op( SOUND_BALLDESTROYED1 )\
	op( SOUND_BALLDESTROYED2 )\
	op( SOUND_BALLDESTROYED3 )\
	op( SOUND_BALLDESTROYED4 )\
	op( SOUND_BALLDESTROYED5 )\
	op( SOUND_COMBO )\
	\
	op( SOUND_BUTTON1 )\
	op( SOUND_BUTTON2 )\
	op( SOUND_CHORAL1 )\
	op( SOUND_POP )\
	op( SOUND_UFO )\
	\
	op( FONT_HUGE )\
	op( FONT_BROWNTITLE )\
	op( FONT_FLOAT )\
	op( FONT_PLAIN )\
	op( FONT_MAIN10 )\
	op( FONT_TITLE )

#define EnumOp( A ) A ,
namespace Zuma
{
	enum  ResID
	{
		RES_ID_LIST( EnumOp )
		RES_NUM_RESOURCES ,
	};

}//namespace Zuma
#undef EnumOp

#endif // ResID_h__



